name: Auto Rerun Triggered by Comment
on:
  repository_dispatch:
    types: [rerun-command]

jobs:
  rerun_failed:
    name: Rerun Failed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: |
          python3 rerun-failed.py "${{ github.event.client_payload.pull_request.html_url }}" ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GARDENER_PAT }}
