name: Auto Land ghstack PRs
on:
  repository_dispatch:
    types: [land-command]

jobs:
  show_environ:
    name: Show Environment Variables
    runs-on: ubuntu-latest
    steps:
    - name: Environment Variables
      run: env
    - name: Github Object
      run: |
        cat <<'EOF'
        ${{ toJson(github) }}
        EOF

  ghstack_land:
    name: ghstack Land
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: |
          python3 ghstack-land.py "${{ github.event.client_payload.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GARDENER_PAT }}
